packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@nestjs/core'

onlyBuiltDependencies:
  - '@openapitools/openapi-generator-cli'
  - esbuild

overrides:
  vite: npm:rolldown-vite@7.2.5
