// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/magic": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/auth" | "/auth/login" | "/auth/magic" | "/*";
  };
  "pages/dashboard.tsx": {
    id: "pages/dashboard";
    page: "/dashboard";
  };
  "pages/_index.tsx": {
    id: "pages/_index";
    page: "/";
  };
  "pages/auth/route.tsx": {
    id: "pages/auth";
    page: "/auth" | "/auth/login" | "/auth/magic";
  };
  "pages/auth._index/route.tsx": {
    id: "pages/auth._index";
    page: "/auth";
  };
  "pages/auth.login/route.tsx": {
    id: "pages/auth.login";
    page: "/auth/login";
  };
  "pages/auth.magic/route.tsx": {
    id: "pages/auth.magic";
    page: "/auth/magic";
  };
  "pages/$.tsx": {
    id: "pages/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/dashboard": typeof import("./src/pages/dashboard.tsx");
  "pages/_index": typeof import("./src/pages/_index.tsx");
  "pages/auth": typeof import("./src/pages/auth/route.tsx");
  "pages/auth._index": typeof import("./src/pages/auth._index/route.tsx");
  "pages/auth.login": typeof import("./src/pages/auth.login/route.tsx");
  "pages/auth.magic": typeof import("./src/pages/auth.magic/route.tsx");
  "pages/$": typeof import("./src/pages/$.tsx");
};