// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/not-found": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/not-found" | "/*";
  };
  "pages/dashboard.tsx": {
    id: "pages/dashboard";
    page: "/dashboard";
  };
  "pages/not-found.tsx": {
    id: "pages/not-found";
    page: "/not-found";
  };
  "pages/_index.tsx": {
    id: "pages/_index";
    page: "/";
  };
  "pages/$.tsx": {
    id: "pages/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/dashboard": typeof import("./src/pages/dashboard.tsx");
  "pages/not-found": typeof import("./src/pages/not-found.tsx");
  "pages/_index": typeof import("./src/pages/_index.tsx");
  "pages/$": typeof import("./src/pages/$.tsx");
};